from io import BytesIO
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
)
from reportlab.pdfbase.pdfmetrics import stringWidth


# =========================================================
# HELPERS
# =========================================================

def safe_text(value, default="N/A"):
    """
    Convert values into safe text for the PDF.
    """
    if value is None or value == "":
        return default

    return str(value)


def format_timestamp(timestamp):
    """
    Make ISO timestamps easier to read.
    """
    if not timestamp:
        return "N/A"

    try:
        value = timestamp.replace("Z", "+00:00")
        dt = datetime.fromisoformat(value)

        return dt.strftime("%d %b %Y, %H:%M UTC")

    except Exception:
        return str(timestamp)


def get_check_name(check):
    """
    Extract a readable security-check name from a check dictionary.
    """

    if not isinstance(check, dict):
        return str(check)

    return (
        check.get("header")
        or check.get("name")
        or check.get("check")
        or check.get("title")
        or "Security Check"
    )


def get_check_severity(check):
    """
    Extract severity if available.
    """

    if not isinstance(check, dict):
        return "N/A"

    return safe_text(
        check.get("severity"),
        "N/A"
    )


def get_check_recommendation(check):
    """
    Extract recommendation if available.
    """

    if not isinstance(check, dict):
        return "N/A"

    return safe_text(
        check.get("recommendation")
        or check.get("description")
        or check.get("message"),
        "N/A"
    )


# =========================================================
# PDF PAGE HEADER / FOOTER
# =========================================================

def draw_page(canvas, document):
    """
    Draw header and footer on every PDF page.
    """

    canvas.saveState()

    width, height = A4

    # -----------------------------------------------------
    # Header
    # -----------------------------------------------------

    canvas.setStrokeColor(colors.HexColor("#e2e8f0"))
    canvas.setLineWidth(0.5)

    canvas.line(
        18 * mm,
        height - 15 * mm,
        width - 18 * mm,
        height - 15 * mm
    )

    canvas.setFont("Helvetica-Bold", 9)
    canvas.setFillColor(colors.HexColor("#0f172a"))

    canvas.drawString(
        18 * mm,
        height - 11 * mm,
        "VulnScan Lite"
    )

    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor("#64748b"))

    canvas.drawRightString(
        width - 18 * mm,
        height - 11 * mm,
        "Passive Web Security Scanner"
    )

    # -----------------------------------------------------
    # Footer
    # -----------------------------------------------------

    canvas.line(
        18 * mm,
        14 * mm,
        width - 18 * mm,
        14 * mm
    )

    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor("#64748b"))

    canvas.drawString(
        18 * mm,
        9 * mm,
        "Generated by VulnScan Lite"
    )

    canvas.drawRightString(
        width - 18 * mm,
        9 * mm,
        f"Page {document.page}"
    )

    canvas.restoreState()


# =========================================================
# MAIN PDF GENERATOR
# =========================================================

def generate_security_report(scan_result):
    """
    Generate a PDF security report from a completed
    VulnScan Lite scan result.

    Returns:
        BytesIO containing the generated PDF.
    """

    buffer = BytesIO()

    document = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=18 * mm,
        leftMargin=18 * mm,
        topMargin=24 * mm,
        bottomMargin=20 * mm,
        title="VulnScan Lite Security Report",
        author="VulnScan Lite",
    )

    styles = getSampleStyleSheet()

    # =====================================================
    # CUSTOM STYLES
    # =====================================================

    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=24,
        leading=28,
        textColor=colors.HexColor("#0f172a"),
        alignment=TA_LEFT,
        spaceAfter=6,
    )

    subtitle_style = ParagraphStyle(
        "ReportSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#64748b"),
        spaceAfter=16,
    )

    section_style = ParagraphStyle(
        "SectionTitle",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=14,
        leading=18,
        textColor=colors.HexColor("#0f172a"),
        spaceBefore=12,
        spaceAfter=8,
    )

    normal_style = ParagraphStyle(
        "ReportNormal",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=14,
        textColor=colors.HexColor("#334155"),
    )

    small_style = ParagraphStyle(
        "ReportSmall",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8,
        leading=11,
        textColor=colors.HexColor("#475569"),
    )

    white_style = ParagraphStyle(
        "WhiteText",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=10,
        textColor=colors.white,
    )

    # =====================================================
    # READ SCAN RESULT
    # =====================================================

    url = safe_text(scan_result.get("url"))
    timestamp = format_timestamp(
        scan_result.get("timestamp")
    )

    score = safe_text(
        scan_result.get("overall_score"),
        "0"
    )

    grade = safe_text(
        scan_result.get("grade"),
        "N/A"
    )

    risk_level = safe_text(
        scan_result.get("risk_level"),
        "Unknown"
    )

    summary = scan_result.get("summary", {}) or {}

    passed_checks = summary.get(
        "passed_checks",
        0
    )

    failed_checks = summary.get(
        "failed_checks",
        0
    )

    ssl_enabled = summary.get(
        "ssl_enabled",
        False
    )

    cms_detected = summary.get(
        "cms_detected",
        False
    )

    recommendation = summary.get(
        "recommendation",
        "No recommendation available."
    )

    headers = scan_result.get(
        "headers",
        {}
    ) or {}

    passed_header_checks = headers.get(
        "passed_checks",
        []
    ) or []

    failed_header_checks = headers.get(
        "failed_checks",
        []
    ) or []

    ssl = scan_result.get(
        "ssl",
        {}
    ) or {}

    cms = scan_result.get(
        "cms",
        {}
    ) or {}

    # =====================================================
    # DOCUMENT CONTENT
    # =====================================================

    story = []

    # -----------------------------------------------------
    # Title
    # -----------------------------------------------------

    story.append(
        Paragraph(
            "Security Health Report",
            title_style
        )
    )

    story.append(
        Paragraph(
            "Passive security assessment generated by VulnScan Lite",
            subtitle_style
        )
    )

    # -----------------------------------------------------
    # Target Information
    # -----------------------------------------------------

    story.append(
        Paragraph(
            "Scan Information",
            section_style
        )
    )

    scan_info = [
        [
            Paragraph("<b>Target URL</b>", normal_style),
            Paragraph(
                safe_text(url),
                normal_style
            ),
        ],
        [
            Paragraph("<b>Scan Time</b>", normal_style),
            Paragraph(
                timestamp,
                normal_style
            ),
        ],
    ]

    info_table = Table(
        scan_info,
        colWidths=[42 * mm, 125 * mm]
    )

    info_table.setStyle(
        TableStyle([
            (
                "BACKGROUND",
                (0, 0),
                (0, -1),
                colors.HexColor("#f8fafc")
            ),
            (
                "BOX",
                (0, 0),
                (-1, -1),
                0.6,
                colors.HexColor("#e2e8f0")
            ),
            (
                "INNERGRID",
                (0, 0),
                (-1, -1),
                0.4,
                colors.HexColor("#e2e8f0")
            ),
            (
                "VALIGN",
                (0, 0),
                (-1, -1),
                "MIDDLE"
            ),
            (
                "LEFTPADDING",
                (0, 0),
                (-1, -1),
                8
            ),
            (
                "RIGHTPADDING",
                (0, 0),
                (-1, -1),
                8
            ),
            (
                "TOPPADDING",
                (0, 0),
                (-1, -1),
                7
            ),
            (
                "BOTTOMPADDING",
                (0, 0),
                (-1, -1),
                7
            ),
        ])
    )

    story.append(info_table)
    story.append(Spacer(1, 10))

    # -----------------------------------------------------
    # Overall Score
    # -----------------------------------------------------

    story.append(
        Paragraph(
            "Overall Security Assessment",
            section_style
        )
    )

    score_data = [
        [
            Paragraph(
                "<b>SECURITY SCORE</b>",
                white_style
            ),
            Paragraph(
                "<b>GRADE</b>",
                white_style
            ),
            Paragraph(
                "<b>RISK LEVEL</b>",
                white_style
            ),
        ],
        [
            Paragraph(
                f"<b>{score} / 100</b>",
                ParagraphStyle(
                    "BigScore",
                    parent=normal_style,
                    fontSize=18,
                    textColor=colors.HexColor("#0f172a"),
                )
            ),
            Paragraph(
                f"<b>{grade}</b>",
                ParagraphStyle(
                    "Grade",
                    parent=normal_style,
                    fontSize=14,
                    textColor=colors.HexColor("#0f172a"),
                )
            ),
            Paragraph(
                f"<b>{risk_level}</b>",
                ParagraphStyle(
                    "Risk",
                    parent=normal_style,
                    fontSize=12,
                    textColor=colors.HexColor("#0f172a"),
                )
            ),
        ],
    ]

    score_table = Table(
        score_data,
        colWidths=[
            55 * mm,
            55 * mm,
            57 * mm
        ]
    )

    score_table.setStyle(
        TableStyle([
            (
                "BACKGROUND",
                (0, 0),
                (-1, 0),
                colors.HexColor("#0f172a")
            ),
            (
                "BACKGROUND",
                (0, 1),
                (-1, 1),
                colors.HexColor("#f8fafc")
            ),
            (
                "BOX",
                (0, 0),
                (-1, -1),
                0.7,
                colors.HexColor("#cbd5e1")
            ),
            (
                "INNERGRID",
                (0, 0),
                (-1, -1),
                0.5,
                colors.HexColor("#e2e8f0")
            ),
            (
                "ALIGN",
                (0, 0),
                (-1, -1),
                "CENTER"
            ),
            (
                "VALIGN",
                (0, 0),
                (-1, -1),
                "MIDDLE"
            ),
            (
                "TOPPADDING",
                (0, 0),
                (-1, -1),
                10
            ),
            (
                "BOTTOMPADDING",
                (0, 0),
                (-1, -1),
                10
            ),
        ])
    )

    story.append(score_table)
    story.append(Spacer(1, 12))

    # -----------------------------------------------------
    # Summary
    # -----------------------------------------------------

    story.append(
        Paragraph(
            "Executive Summary",
            section_style
        )
    )

    summary_data = [
        ["Metric", "Result"],
        [
            "Passed Checks",
            safe_text(passed_checks, "0")
        ],
        [
            "Failed Checks",
            safe_text(failed_checks, "0")
        ],
        [
            "SSL/TLS",
            "Enabled" if ssl_enabled else "Disabled"
        ],
        [
            "CMS",
            "Detected" if cms_detected else "Not Detected"
        ],
    ]

    summary_table = Table(
        summary_data,
        colWidths=[
            80 * mm,
            87 * mm
        ]
    )

    summary_table.setStyle(
        TableStyle([
            (
                "BACKGROUND",
                (0, 0),
                (-1, 0),
                colors.HexColor("#e2e8f0")
            ),
            (
                "FONTNAME",
                (0, 0),
                (-1, 0),
                "Helvetica-Bold"
            ),
            (
                "TEXTCOLOR",
                (0, 0),
                (-1, 0),
                colors.HexColor("#0f172a")
            ),
            (
                "GRID",
                (0, 0),
                (-1, -1),
                0.5,
                colors.HexColor("#cbd5e1")
            ),
            (
                "BACKGROUND",
                (0, 1),
                (-1, -1),
                colors.white
            ),
            (
                "FONTNAME",
                (0, 1),
                (-1, -1),
                "Helvetica"
            ),
            (
                "FONTSIZE",
                (0, 0),
                (-1, -1),
                9
            ),
            (
                "TEXTCOLOR",
                (0, 1),
                (-1, -1),
                colors.HexColor("#334155")
            ),
            (
                "VALIGN",
                (0, 0),
                (-1, -1),
                "MIDDLE"
            ),
            (
                "TOPPADDING",
                (0, 0),
                (-1, -1),
                7
            ),
            (
                "BOTTOMPADDING",
                (0, 0),
                (-1, -1),
                7
            ),
            (
                "LEFTPADDING",
                (0, 0),
                (-1, -1),
                7
            ),
        ])
    )

    story.append(summary_table)
    story.append(Spacer(1, 12))

    # -----------------------------------------------------
    # Recommendation
    # -----------------------------------------------------

    story.append(
        Paragraph(
            "Recommendation",
            section_style
        )
    )

    recommendation_table = Table(
        [[
            Paragraph(
                safe_text(
                    recommendation,
                    "No recommendation available."
                ),
                normal_style
            )
        ]],
        colWidths=[167 * mm]
    )

    recommendation_table.setStyle(
        TableStyle([
            (
                "BACKGROUND",
                (0, 0),
                (-1, -1),
                colors.HexColor("#f8fafc")
            ),
            (
                "BOX",
                (0, 0),
                (-1, -1),
                0.6,
                colors.HexColor("#cbd5e1")
            ),
            (
                "LEFTPADDING",
                (0, 0),
                (-1, -1),
                10
            ),
            (
                "RIGHTPADDING",
                (0, 0),
                (-1, -1),
                10
            ),
            (
                "TOPPADDING",
                (0, 0),
                (-1, -1),
                10
            ),
            (
                "BOTTOMPADDING",
                (0, 0),
                (-1, -1),
                10
            ),
        ])
    )

    story.append(recommendation_table)

    # =====================================================
    # SECURITY HEADERS
    # =====================================================

    story.append(
        Paragraph(
            "Security Header Analysis",
            section_style
        )
    )

    # -----------------------------------------------------
    # Passed Headers
    # -----------------------------------------------------

    if passed_header_checks:

        story.append(
            Paragraph(
                "Passed Security Checks",
                ParagraphStyle(
                    "PassedHeading",
                    parent=normal_style,
                    fontName="Helvetica-Bold",
                    fontSize=10,
                    textColor=colors.HexColor("#15803d"),
                    spaceAfter=5,
                )
            )
        )

        passed_data = [
            [
                "Security Check",
                "Status"
            ]
        ]

        for check in passed_header_checks:

            passed_data.append([
                Paragraph(
                    safe_text(
                        get_check_name(check)
                    ),
                    small_style
                ),
                Paragraph(
                    "PASS",
                    ParagraphStyle(
                        "PassText",
                        parent=small_style,
                        fontName="Helvetica-Bold",
                        textColor=colors.HexColor("#15803d"),
                    )
                ),
            ])

        passed_table = Table(
            passed_data,
            colWidths=[
                130 * mm,
                37 * mm
            ]
        )

        passed_table.setStyle(
            TableStyle([
                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, 0),
                    colors.HexColor("#dcfce7")
                ),
                (
                    "TEXTCOLOR",
                    (0, 0),
                    (-1, 0),
                    colors.HexColor("#166534")
                ),
                (
                    "FONTNAME",
                    (0, 0),
                    (-1, 0),
                    "Helvetica-Bold"
                ),
                (
                    "GRID",
                    (0, 0),
                    (-1, -1),
                    0.5,
                    colors.HexColor("#d1d5db")
                ),
                (
                    "VALIGN",
                    (0, 0),
                    (-1, -1),
                    "MIDDLE"
                ),
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    7
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    7
                ),
            ])
        )

        story.append(passed_table)
        story.append(Spacer(1, 10))

    # -----------------------------------------------------
    # Failed Headers
    # -----------------------------------------------------

    if failed_header_checks:

        story.append(
            Paragraph(
                "Failed Security Checks",
                ParagraphStyle(
                    "FailedHeading",
                    parent=normal_style,
                    fontName="Helvetica-Bold",
                    fontSize=10,
                    textColor=colors.HexColor("#b91c1c"),
                    spaceAfter=5,
                )
            )
        )

        failed_data = [
            [
                "Security Check",
                "Severity",
                "Recommendation"
            ]
        ]

        for check in failed_header_checks:

            failed_data.append([
                Paragraph(
                    safe_text(
                        get_check_name(check)
                    ),
                    small_style
                ),
                Paragraph(
                    safe_text(
                        get_check_severity(check)
                    ),
                    small_style
                ),
                Paragraph(
                    safe_text(
                        get_check_recommendation(check)
                    ),
                    small_style
                ),
            ])

        failed_table = Table(
            failed_data,
            colWidths=[
                45 * mm,
                30 * mm,
                92 * mm
            ],
            repeatRows=1
        )

        failed_table.setStyle(
            TableStyle([
                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, 0),
                    colors.HexColor("#fee2e2")
                ),
                (
                    "TEXTCOLOR",
                    (0, 0),
                    (-1, 0),
                    colors.HexColor("#991b1b")
                ),
                (
                    "FONTNAME",
                    (0, 0),
                    (-1, 0),
                    "Helvetica-Bold"
                ),
                (
                    "GRID",
                    (0, 0),
                    (-1, -1),
                    0.5,
                    colors.HexColor("#d1d5db")
                ),
                (
                    "VALIGN",
                    (0, 0),
                    (-1, -1),
                    "TOP"
                ),
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    7
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    7
                ),
            ])
        )

        story.append(failed_table)

    # =====================================================
    # SSL/TLS
    # =====================================================

    story.append(
        Paragraph(
            "SSL/TLS Analysis",
            section_style
        )
    )

    ssl_status = (
        "Enabled"
        if ssl.get("enabled")
        else "Disabled"
    )

    ssl_valid = (
        "Valid"
        if ssl.get("valid")
        else "Invalid / Not Available"
    )

    ssl_data = [
        ["Property", "Value"],
        [
            "SSL/TLS Status",
            ssl_status
        ],
        [
            "Certificate Status",
            ssl_valid
        ],
        [
            "Issuer",
            safe_text(
                ssl.get("issuer")
            )
        ],
        [
            "Subject",
            safe_text(
                ssl.get("subject")
            )
        ],
        [
            "Expiration",
            safe_text(
                ssl.get("expires")
            )
        ],
        [
            "Days Remaining",
            safe_text(
                ssl.get("days_remaining")
            )
        ],
    ]

    ssl_table = Table(
        ssl_data,
        colWidths=[
            60 * mm,
            107 * mm
        ]
    )

    ssl_table.setStyle(
        TableStyle([
            (
                "BACKGROUND",
                (0, 0),
                (-1, 0),
                colors.HexColor("#e0f2fe")
            ),
            (
                "FONTNAME",
                (0, 0),
                (-1, 0),
                "Helvetica-Bold"
            ),
            (
                "TEXTCOLOR",
                (0, 0),
                (-1, 0),
                colors.HexColor("#0c4a6e")
            ),
            (
                "GRID",
                (0, 0),
                (-1, -1),
                0.5,
                colors.HexColor("#cbd5e1")
            ),
            (
                "VALIGN",
                (0, 0),
                (-1, -1),
                "MIDDLE"
            ),
            (
                "TOPPADDING",
                (0, 0),
                (-1, -1),
                7
            ),
            (
                "BOTTOMPADDING",
                (0, 0),
                (-1, -1),
                7
            ),
        ])
    )

    story.append(ssl_table)

    # =====================================================
    # CMS
    # =====================================================

    story.append(
        Paragraph(
            "CMS Detection",
            section_style
        )
    )

    cms_status = (
        "Detected"
        if cms.get("detected")
        else "Not Detected"
    )

    cms_data = [
        ["Property", "Value"],
        [
            "Detection Status",
            cms_status
        ],
        [
            "CMS Name",
            safe_text(
                cms.get("name")
            )
        ],
        [
            "Version",
            safe_text(
                cms.get("version")
            )
        ],
    ]

    cms_table = Table(
        cms_data,
        colWidths=[
            60 * mm,
            107 * mm
        ]
    )

    cms_table.setStyle(
        TableStyle([
            (
                "BACKGROUND",
                (0, 0),
                (-1, 0),
                colors.HexColor("#f1f5f9")
            ),
            (
                "FONTNAME",
                (0, 0),
                (-1, 0),
                "Helvetica-Bold"
            ),
            (
                "GRID",
                (0, 0),
                (-1, -1),
                0.5,
                colors.HexColor("#cbd5e1")
            ),
            (
                "VALIGN",
                (0, 0),
                (-1, -1),
                "MIDDLE"
            ),
            (
                "TOPPADDING",
                (0, 0),
                (-1, -1),
                7
            ),
            (
                "BOTTOMPADDING",
                (0, 0),
                (-1, -1),
                7
            ),
        ])
    )

    story.append(cms_table)

    # =====================================================
    # DISCLAIMER
    # =====================================================

    story.append(Spacer(1, 15))

    story.append(
        Paragraph(
            "<b>Important:</b> VulnScan Lite performs passive "
            "security checks. This report does not represent "
            "a complete penetration test or guarantee that a "
            "website is free from vulnerabilities.",
            ParagraphStyle(
                "Disclaimer",
                parent=small_style,
                textColor=colors.HexColor("#64748b"),
                leading=12,
            )
        )
    )

    # =====================================================
    # BUILD PDF
    # =====================================================

    document.build(
        story,
        onFirstPage=draw_page,
        onLaterPages=draw_page
    )

    buffer.seek(0)

    return buffer